services:
  - type: web
    name: med-herbs
    env: python
    rootDir: backend
    buildCommand: pip install -r ../requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MYSQL_HOST
        value: ${MYSQL_HOST}  # Gamitin ang value mula sa .env
      - key: MYSQL_USER
        value: ${MYSQL_USER}  # Gamitin ang value mula sa .env
      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}  # Gamitin ang value mula sa .env
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}  # Gamitin ang value mula sa .env
      - key: SECRET_KEY
        value: ${SECRET_KEY}  # Gamitin ang value mula sa .env
