services:
  - type: web
    name: med-herbs
    env: python
    buildCommand: pip install -r requirements.txt  # Nasa root directory
    startCommand: gunicorn backend.app:app  # Flask app ay nasa 'backend' folder
    envVars:
      - key: FLASK_ENV
        value: production
